version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5438:5432'
    environment:
      POSTGRES_PASSWORD: ${pass}
      POSTGRES_DB: ${name}
    container_name: travel_ticket_db
    volumes: 
      - ./postgres:/var/lib/postgresql/data